### ISSUE TITLE
Syntax error on line 43 "except Exception, 3:"

### ISSUE THREAD

**Issue by brawth** [lob/lob-python#125]
afternoon.  we seem to be getting an error on the preceding line.  any help would be appreciated!

**Comment by dmlittle** [comment]
Hi @brawth, can you provide any context on where the error is occurring? What code is producing the error? Does the error occur in within the lob-python wrapper or the code utilizing it? What version of python and OS are you using?

**Comment by brawth** [comment]
Hey there!  I'll provide a screen cap!  Seems to be in the code (I was very
careful in making sure I was copy+pasting from github to note break
formatting)

I'm currently using python 3.6 using the Spyder^3 idle.  Windows 10.

**Comment by chrisisr** [comment]
.Traceback (most recent call last):
File "verify.py", line 50, in <module>
address_country = country
File "/Users/Main/anaconda/lib/python3.6/site-packages/lob/resource.py", line 125, in create
response = requestor.request('post', cls.endpoint, params)
File "/Users/Main/anaconda/lib/python3.6/site-packages/lob/api_requestor.py", line 84, in request
requests.post(lob.api_base + url, auth=(self.api_key, ''), data=data, files=files, headers=headers)
File "/Users/Main/anaconda/lib/python3.6/site-packages/lob/api_requestor.py", line 37, in parse_response
resp.content, resp.status_code, resp)
lob.error.InvalidRequestError: address_zip length must be less than or equal to 12 characters long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "verify.py", line 52, in <module>
except(Exception, e):
NameError: name 'e' is not defined

I get these errors when trying to run the block. the most glaring being that 'e is not defined. why is this an issue?

**Comment by dmlittle** [comment]
@brawth & @chrisisr, it seems our wrapper examples weren't compatible with Python3.

I've gone ahead and updated all of our [examples](https://github.com/lob/lob-python/tree/master/examples) to work with both Python2 and Python3. Feel free to use them as reference as they should be working now. 

I can't see what your code looks like but exceptions in Python 3 (that are also compatible with Python2) use the following syntax:
```python
try:
  # code block
except Exception as e:
  print("Oops! Something went wrong.")
  print(e)
 ```

**Comment by brawth** [comment]
thanks !

**Comment by dmlittle** [comment]
I'll be closing this issue now. Feel free to open another issue or contact support@lob.com if you have any other questions.

**Comment by chrisisr** [comment]
thank you! that is very much appreciated.
