### ISSUE TITLE
import issue on AWS Lambda

### ISSUE THREAD

**Issue by jacobrharris** [lob/lob-python#132]
I get this error when trying to import lob on AWS Lambda: `Unable to import module 'lambda_function': No module named lob.resource`

One thing I'm doing that might be throwing it off is I'm installing the libraries in a subdirectory using this command: `pip install -t libs/ lob`. There is an `__init.py__` file in that `libs` directory, and that allows me to import other libraries successfully (PyMySQL, braintree, etc.) using `from libs import blah`. But lob doesn't seem to like being imported that way.

I've attached a .zip of my file structure for reference.

[lob_test.zip](https://github.com/lob/lob-python/files/1177601/lob_test.zip)

**Comment by jacobrharris** [comment]
One additional piece of info...

If I add this to the import:

```
import sys
sys.path.append('libs')
```

That allows the import to work, but then I get this authentication error:

`Your API key is not valid. Please sign up on lob.com to get a valid api key.: AuthenticationError`

**Comment by isaacdchan** [comment]
How did you manage to successfully import pymysql? I don't know if it's a version error, dependency error (idna/requests) or packaging error. I think I've zipped the files correctly but am not sure.

**Comment by pdufour** [comment]
Closed due to inactivity, if it is still an issue please re-open. Thank you!

**Comment by dharantejv** [comment]
![image](https://user-images.githubusercontent.com/72353996/115387916-e623cf80-a1f8-11eb-84cb-f5abf3a09c97.png)
iam getting this error
Your API key is not valid. Please sign up on lob.com to get a valid api key.: AuthenticationError

**Comment by dharantejv** [comment]
can anyone help me please to solve the error
