### ISSUE TITLE
Ink-Free Area Alignment

### ISSUE THREAD

**Issue by namwen** [lob/lob-python#152]
Posting here because the /examples repo doesn't have issues enabled.

When using the example 4x6 back template (https://github.com/lob/examples/blob/master/postcards/4x6-back.html), the recipient address / Postage Indicia section is not aligned with the area specified in the template.

I've included a screenshot of the postcard created using the template. I set a black border on the ink-free div in the template to judge where I can place assets. The white address box is about a centimeter off from where it should be according to the template's CSS. 

This is obviously easy enough to fix in CSS, but I'm not sure who to trust: the template or the postcard created in test mode.

![screen shot 2018-12-20 at 3 12 26 pm](https://user-images.githubusercontent.com/1923672/50316230-9dae4880-046a-11e9-8fec-d7fad0c83db8.png)

**Comment by ami** [comment]
Hey @namwen!

Can you submit this as a support ticket by contacting our support team at support@lob.com? This does not have to do with the lob python library.

Thanks!
