### ISSUE TITLE
lob API returning 503 throws

### ISSUE THREAD

**Issue by justmobilize** [lob/lob-python#156]
After your **planned maintenance** the other day, can you update `/lob/api_requestor.py`, `parse_response` to support `503`? Otherwise `payload = resp.json()` throws.

**Comment by UjjwalAyyangar** [comment]
@justmobilize Are you still experiencing this issue? 

`payload = resp.json()` is only thrown when the status is `200`, for 503 it raises `APIError` with appropriate message

**Comment by UjjwalAyyangar** [comment]
Agreed. 
@ami is anyone working on this?
If no, then I can send in a pull request to fix this.

**Comment by pdufour** [comment]
Closed due to inactivity, if it is still an issue please re-open. Thank you!

**Comment by justmobilize** [comment]
This is still an issue @pdufour
