### ISSUE TITLE
Cannot retrieve Bank Account Information or Send Checks using lob_python

### ISSUE THREAD

**Issue by eyurtsev** [lob/lob-python#190]
Getting a failure while attempting to retrieve bank account information in the `test` environment.  

```
with lob_python.ApiClient(configuration) as lob_client:
    bank_account_id = "xxxxxxxxxx"
    accounts_api = BankAccountsApi(lob_client)
```

The issue seems to appear when using `PNG` signature, and occurs due to incorrect regex used to validate `signature_url`  here: https://github.com/lob/lob-python/blob/main/lob_python/model/bank_account.py#L87

Our signature_url looks like so:

```
https://lob-assets.com/bank-accounts/bank_xxxxxxxxxx_signature.png?ve.....
```

The regular expression is looking for "thumb" which doesn't appear (there may be additional issues with it).

```
        ('signature_url',): {
            'regex': {
                'pattern': r'^https:\/\/lob-assets\.com\/(letters|postcards|bank-accounts|checks|self-mailers|cards)\/[a-z]{3,4}_[a-z0-9]{15,16}(\.pdf|_thumb_[a-z]+_[0-9]+\.png)\?(version=[a-z0-9-]*&)?expires=[0-9]{10}&signature=[a-zA-Z0-9-_]+$',  # noqa: E501
            },
        },
```

--------------

This prevents sending of checks as well as the check api seems to use the same validation somewhere in the code path

**Comment by BennyKitchell** [comment]
Hey @eyurtsev 

Thanks for the feedback, I will add this to the next sprint, but will make it my priority for then. I will update this issue when that has been resolved.

**Comment by eyurtsev** [comment]
For anyone bumping into this issue in the meantime, pattern validation can be disabled client side

```
configuration = lob_python.Configuration(
    username='secret_token',
    disabled_client_side_validations="pattern",
)
```

@BennyKitchell we double checked the dashboard, and as far as we can tell default signatures are all PNGs rather than PDFs

**Comment by BennyKitchell** [comment]
@eyurtsev  Perfect, I am glad you found a solution on this for now. We have it queued up to work on in the next sprint to remove the `thumb` requirement. I will update when that change is live.

**Comment by BennyKitchell** [comment]
Hi @eyurtsev,

This change is now live with version 5.0.1, as we discussed I removed the *_thumb_* requirement from the file name. 
I will leave this issue open for a few days in case something isn't working as expected. Thanks!

**Comment by pbanh-jsq** [comment]
@BennyKitchell, I noticed that the regex was reverted, was this intended?

I believe I'm currently seeing the same error reported above
