### ISSUE TITLE
Check validation fails for certain valid amounts, but check is sent anyway

### ISSUE THREAD

**Issue by jhhayashi** [lob/lob-python#194]
https://github.com/lob/lob-python/blob/main/lob_python/model_utils.py#L918

This line does not correctly determine whether a number is a valid amount. With the imprecision of floating point arithmetic, there will be many cases where dividing a valid `amount` by `0.01` will result in a non-integer:

```python
>>> 0.14 / 0.01
14.000000000000002
>>> (0.14 / 0.01).is_integer()
False
```

I scripted a quick test and it seems like 10-20% of valid numbers will fail this check.

Additionally, when I ran into a failed validation, the check was still sent even though the SDK errored.

**Comment by BennyKitchell** [comment]
Hey @jhhayashi 

Thanks for reaching out, that's a great catch on your part. I am going to investigate a solution to this and try to get a fix out within the next week. I will update this ticket whenever that release has been pushed out.

**Comment by BennyKitchell** [comment]
Hi @jhhayashi ,

This change is now live with version 5.0.1, we have updated that code as discussed.
I will leave this issue open for a few days in case something isn't working as expected. Thanks!
