### ISSUE TITLE
Add individual examples to examples folder

### ISSUE THREAD

**Issue by leore** [lob/lob-python#34]

**Comment by elnaz** [comment]
Hey @leore, Could you bring me up to speed with the specifics of what you wanted done for this issue?

**Comment by russelltaylor05** [comment]
@leore @elnaz 

Not sure what you guys are doing here, but I think it makes sense to move my Python Examples stuff in here and clean up the directory with proper READMEs and links back to the main site (SEO juice)

https://github.com/lob/python-examples

**Comment by elnaz** [comment]
@leore Here's the state of the examples now that we've added letters.py and used html, data, custom fonts, and metadata in the other examples https://github.com/lob/lob-python/tree/master/examples. What else should be done or is this task considered complete?

**Comment by leore** [comment]
Is there an example of sending postcards or letters from a CSV?

**Comment by pon** [comment]
Let's close this issue - I'll open issues for next wrapper day to do CSV/HTML exam,ples in all languages
