### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by seanfisher** [lob/lob-python#62]
Hello,

I'm relatively new to Python development, and when I try to import `lob` into a Python3 project I get
```
File "/usr/local/opt/pyenv/versions/3.4.2/lib/python3.4/site-packages/lob/__init__.py", line 5, in <module>
    from lob.resource import (Address, Area, BankAccount, Check, Country, Job,
  File "/usr/local/opt/pyenv/versions/3.4.2/lib/python3.4/site-packages/lob/resource.py", line 62
    except KeyError, err:
                   ^
SyntaxError: invalid syntax
```

Is this because this is a python 2 package? Is there any easy way to port it to python 3?

Thanks

**Comment by elnaz** [comment]
Hi @seanfisher, Thanks for trying out our Python wrapper. Unfortunately we currently don't have plans to support Python 3.
